[features]
seeds = false
skip-lint = false
[programs.localnet]
farming_idle_program = "RkoKjJ7UVatbVegugEjq11Q5agPynBAZV2VhPrNp5kH"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/mikesulistio/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
